In [1]:
import numpy as np

In [5]:
# numpy에서 사용하는 배열 array 생성하기
# 배열안에 넣을 데이터
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

In [9]:
# np.array() : 배열 생성
arr1 = np.array(list1)
arr2 = np.array(list2)

In [10]:
arr1+arr2        # 각 자리의 수 끼리 더하기

array([ 7,  9, 11, 13, 15])

In [29]:
# 2차원 array 만들기
list2 = [[1,2,3],[4,5,6]]     #2차원 리스트
arr2 = np.array(list2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

 배열의 크기 : shape  
 배열의 차원 : ndim  
 배열 요소의 개수 : size   
   
 배열 생성

In [13]:
arr2.shape

(2, 3)

In [16]:
arr2.ndim

2

In [17]:
arr2.size

6

In [18]:
arr2.dtype

dtype('int32')

In [27]:
# 특정 값으로 배열 생성  ( 139p )
# 0으로 채워진 배열 만들기 : np.zeros(배열크기)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
# 원하는 값으로 배열 만들기 : np.fulll(크기,값)
np.full((4,3),"가")

array([['가', '가', '가'],
       ['가', '가', '가'],
       ['가', '가', '가'],
       ['가', '가', '가']], dtype='<U1')

In [39]:
# 연속적인 값으로 배열 : np.arange(시작,끝,간격)
np.arange(50)+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### 배열 사용하기

In [40]:
#요소별 연산하기

In [45]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.arange(6,11)
arr2

array([ 6,  7,  8,  9, 10])

In [48]:
# 배열로 다시 배열 만들기
np.vstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [50]:
# 인덱싱 / 슬라이싱

In [52]:
arr3 = np.arange(1,7)

In [60]:
# 가지고 있는 배열의 크기를 변경하는 함수
# arr.reshape(배열의 크기)
arr3 = arr3.reshape(2,3)

In [64]:
arr3[1,2] == arr3[1][2]

True

In [65]:
arr4 = np.arange(10)

In [67]:
arr4[4:]

array([4, 5, 6, 7, 8, 9])

In [72]:
arr5 = np.arange(50).reshape(5,10)
arr5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [76]:
arr5[:2,:]   # 행, 열

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [78]:
arr5[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [81]:
arr5[1:4,6:7]  #6만 하면 가로로 나옴 ㅠ

array([[16],
       [26],
       [36]])

In [83]:
# 연결되지않은 여러 값 가져오기
arr5[2,[3,5,7]]   # 행, 열

array([23, 25, 27])

예제

In [86]:
# loadtxt("파일경로",delimiter = ',') : 로컬 폴더에 있는 파일 읽기, ','로 구분
data = np.loadtxt("height_weight.txt", delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [97]:
height = data[0]/100
bmi = data[1]/height/height
bmi

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [98]:
# 인뎅싱, 슬라이싱, 팬시인뎅싱, 불리언인뎅싱(boolean)

In [100]:
# 불리언인뎅싱 : 모든 데이터를 불리언으로 만ㄴ듬
# True는 출력, False는 미출력

In [101]:
arr6 = np.array([1,4,2,3,5])

In [106]:
arr6 > 2

array([False,  True, False,  True,  True])

In [107]:
arr6[arr6>2]

array([4, 3, 5])

In [122]:
arr6[(arr6 > 2) &(arr6<4)]

array([3])

In [124]:
arr6[(arr6 > 2) and (arr6<4)]    # True False를 구분하기때문에 에러

In [133]:
# 계산 함수들 : sum, mean, sqrt 등  ( p160 )
# 계산함수 : 유니버셜 함수 : 배열의 각 원소를 빠르게 처리하는 함수
arr6.sum()

15

In [131]:
print(arr3,',')
print(arr3.sum(),',')
print(arr3.sum(axis=0),',')
arr3.sum(axis=1)

[[1 2 3]
 [4 5 6]] ,
21 ,
[5 7 9] ,


array([ 6, 15])

##### 실습
- 1. 전체 평점(3열) 평균 구하기
- 2. user_id(1열)가 1인 데이터의 평점 평균 구하기 ( Hint : 불리언 인덱싱 )
- 3. 각 사용자별 평점 평균 구하기 ( 2번의 연장선 ), np.array에 저장
- 4. 평균 평점이 4점 이상인 사용자 구하기

In [137]:
import numpy as np

In [139]:
data = np.loadtxt("ratings.txt", delimiter='::',dtype='int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [140]:
print(data.shape)
print(data.ndim)
print(data.size)

(1000209, 4)
2
4000836


In [143]:
# 1
arr1 = data[:,2]
arr1.mean()

3.581564453029317

In [158]:
# 2
arr2 = data[:,[0,2]]
bol = arr2[:,0]==1
arr2 = arr2[bol]
arr2[:,1].mean()

4.188679245283019

In [167]:
# 3
arr=[]
arr3 = data[:,[0,2]]
for i in range(1,6041):
    bol = arr3[:,0]==i
    arr.append(arr3[bol][:,1].mean())
arr

[4.188679245283019,
 3.7131782945736433,
 3.9019607843137254,
 4.190476190476191,
 3.1464646464646466,
 3.9014084507042255,
 4.32258064516129,
 3.884892086330935,
 3.7358490566037736,
 4.114713216957606,
 3.2773722627737225,
 3.8260869565217392,
 3.388888888888889,
 3.32,
 3.3233830845771144,
 3.0285714285714285,
 4.075829383886256,
 3.6491803278688524,
 3.5725490196078433,
 4.083333333333333,
 2.909090909090909,
 3.0673400673400675,
 3.3157894736842106,
 3.948529411764706,
 3.7411764705882353,
 2.96,
 4.171428571428572,
 3.7570093457943927,
 3.5833333333333335,
 3.488372093023256,
 3.73109243697479,
 3.625,
 3.498721227621483,
 3.8658536585365852,
 3.54040404040404,
 4.199430199430199,
 3.69811320754717,
 3.58,
 3.564516129032258,
 3.4479166666666665,
 3.48,
 3.74025974025974,
 4.125,
 3.6321243523316062,
 2.946127946127946,
 4.219512195121951,
 3.909090909090909,
 3.068561872909699,
 3.712962962962963,
 3.0697674418604652,
 3.825,
 3.5569620253164556,
 4.2368421052631575,
 4.025,
 4.

In [166]:
# 4
arr4 = np.array(arr)
arr4 = arr[arr>=4]
arr4

array([4.18867925, 4.19047619, 4.32258065, ..., 4.25      , 4.13461538,
       4.0952381 ])

In [169]:
# csv파일로 저장 : np.savetxt(내보낼 파일 이름, 내보낼 정보, 구분자, (포맷))
np.savetxt('user_id_mean.csv',arr,delimiter=',',fmt="%.3f") #소수점3자리까지만